# Generated by Django 4.2.4 on 2023-09-15 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_delete_user_rename_description_auth_user_about_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auth_user',
        ),
    ]
