# Generated by Django 4.2.4 on 2023-09-16 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='aboutuser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
