# Generated by Django 4.2.4 on 2023-09-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_userdetail_aboutuser_alter_userdetail_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
