# Generated by Django 4.2.4 on 2023-09-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_blogpost_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='video',
        ),
    ]
