# Generated by Django 4.2.4 on 2023-09-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_blogpost_options_userdetail_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
